---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/MapToHash:
  Exclude:
  - lib/eac_envs/http/response/links.rb
  - lib/eac_envs/http/rspec/echo_server/request_processor.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/eac_envs/http/request/body_fields_spec.rb
  - spec/lib/eac_envs/http/request_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
Style/RedundantRegexpEscape:
  Exclude:
  - lib/eac_envs/http/response/links.rb
Style/StringConcatenation:
  Exclude:
  - lib/eac_envs/http/response/body.rb
  - spec/lib/eac_envs/http/request_spec.rb
