---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantRegexpEscape:
  Exclude:
  - lib/eac_envs/http/response/links.rb
Style/StringConcatenation:
  Exclude:
  - lib/eac_envs/http/response/body.rb
  - spec/lib/eac_envs/http/request_spec.rb
